///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DelTek_POC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DelTek_POCRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("5fdf545d-8175-4dfa-afd5-4019d1273998")]
    public partial class DelTek_POCRepository : RepoGenBaseFolder
    {
        static DelTek_POCRepository instance = new DelTek_POCRepository();
        DelTek_POCRepositoryFolders.TaskbarAppFolder _taskbar;
        DelTek_POCRepositoryFolders.StartAppFolder _start;
        DelTek_POCRepositoryFolders.DHS_FormAppFolder _dhs_form;

        /// <summary>
        /// Gets the singleton class instance representing the DelTek_POCRepository element repository.
        /// </summary>
        [RepositoryFolder("5fdf545d-8175-4dfa-afd5-4019d1273998")]
        public static DelTek_POCRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DelTek_POCRepository() 
            : base("DelTek_POCRepository", "/", null, 0, false, "5fdf545d-8175-4dfa-afd5-4019d1273998", ".\\RepositoryImages\\DelTek_POCRepository5fdf545d.rximgres")
        {
            _taskbar = new DelTek_POCRepositoryFolders.TaskbarAppFolder(this);
            _start = new DelTek_POCRepositoryFolders.StartAppFolder(this);
            _dhs_form = new DelTek_POCRepositoryFolders.DHS_FormAppFolder(this);
        }

#region Variables

        string _varDHSAppName = "";

        /// <summary>
        /// Gets or sets the value of variable varDHSAppName.
        /// </summary>
        [TestVariable("56896e7d-77fe-4eb7-a301-b6ed1d0fb28c")]
        public string varDHSAppName
        {
            get { return _varDHSAppName; }
            set { _varDHSAppName = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5fdf545d-8175-4dfa-afd5-4019d1273998")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Taskbar folder.
        /// </summary>
        [RepositoryFolder("51f4942f-7156-417f-b5c1-89a916ffd715")]
        public virtual DelTek_POCRepositoryFolders.TaskbarAppFolder Taskbar
        {
            get { return _taskbar; }
        }

        /// <summary>
        /// The Start folder.
        /// </summary>
        [RepositoryFolder("bcf9319b-b30d-46ff-be06-e38eefcb8c80")]
        public virtual DelTek_POCRepositoryFolders.StartAppFolder Start
        {
            get { return _start; }
        }

        /// <summary>
        /// The DHS_Form folder.
        /// </summary>
        [RepositoryFolder("7b48ef68-bac7-43b6-8b0c-e24b9cd1e438")]
        public virtual DelTek_POCRepositoryFolders.DHS_FormAppFolder DHS_Form
        {
            get { return _dhs_form; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class DelTek_POCRepositoryFolders
    {
        /// <summary>
        /// The TaskbarAppFolder folder.
        /// </summary>
        [RepositoryFolder("51f4942f-7156-417f-b5c1-89a916ffd715")]
        public partial class TaskbarAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _startInfo;
            RepoItemInfo _dellhelpsupportrunningwindowInfo;
            RepoItemInfo _popupInfo;
            RepoItemInfo _networdiconInfo;

            /// <summary>
            /// Creates a new Taskbar  folder.
            /// </summary>
            public TaskbarAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Taskbar", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "51f4942f-7156-417f-b5c1-89a916ffd715", "")
            {
                _startInfo = new RepoItemInfo(this, "Start", "element[@class='Start']/button", 30000, null, "46cd81ba-7fd9-49b3-902c-11ccbbb3f97c");
                _dellhelpsupportrunningwindowInfo = new RepoItemInfo(this, "DellHelpSupportRunningWindow", ".//toolbar[@accessiblename='Running applications']/button[@accessiblename~'Dell Help & Support - 1 running window']", 30000, null, "cb424b1d-523f-493e-a48c-a130ad77e4c0");
                _popupInfo = new RepoItemInfo(this, "Popup", "?/?/button[@controlid='1502']", 30000, null, "3fb017ea-1791-45aa-ae9f-a55b36722f33");
                _networdiconInfo = new RepoItemInfo(this, "NetwordIcon", "container[@class='TrayNotifyWnd']//button[@commandid='2']", 30000, null, "e90235bb-60b7-429d-aa78-468296038b12");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("51f4942f-7156-417f-b5c1-89a916ffd715")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("51f4942f-7156-417f-b5c1-89a916ffd715")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Start item.
            /// </summary>
            [RepositoryItem("46cd81ba-7fd9-49b3-902c-11ccbbb3f97c")]
            public virtual Ranorex.Button Start
            {
                get
                {
                    return _startInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Start item info.
            /// </summary>
            [RepositoryItemInfo("46cd81ba-7fd9-49b3-902c-11ccbbb3f97c")]
            public virtual RepoItemInfo StartInfo
            {
                get
                {
                    return _startInfo;
                }
            }

            /// <summary>
            /// The DellHelpSupportRunningWindow item.
            /// </summary>
            [RepositoryItem("cb424b1d-523f-493e-a48c-a130ad77e4c0")]
            public virtual Ranorex.Button DellHelpSupportRunningWindow
            {
                get
                {
                    return _dellhelpsupportrunningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DellHelpSupportRunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("cb424b1d-523f-493e-a48c-a130ad77e4c0")]
            public virtual RepoItemInfo DellHelpSupportRunningWindowInfo
            {
                get
                {
                    return _dellhelpsupportrunningwindowInfo;
                }
            }

            /// <summary>
            /// The Popup item.
            /// </summary>
            [RepositoryItem("3fb017ea-1791-45aa-ae9f-a55b36722f33")]
            public virtual Ranorex.Button Popup
            {
                get
                {
                    return _popupInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Popup item info.
            /// </summary>
            [RepositoryItemInfo("3fb017ea-1791-45aa-ae9f-a55b36722f33")]
            public virtual RepoItemInfo PopupInfo
            {
                get
                {
                    return _popupInfo;
                }
            }

            /// <summary>
            /// The NetwordIcon item.
            /// </summary>
            [RepositoryItem("e90235bb-60b7-429d-aa78-468296038b12")]
            public virtual Ranorex.Button NetwordIcon
            {
                get
                {
                    return _networdiconInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NetwordIcon item info.
            /// </summary>
            [RepositoryItemInfo("e90235bb-60b7-429d-aa78-468296038b12")]
            public virtual RepoItemInfo NetwordIconInfo
            {
                get
                {
                    return _networdiconInfo;
                }
            }
        }

        /// <summary>
        /// The StartAppFolder folder.
        /// </summary>
        [RepositoryFolder("bcf9319b-b30d-46ff-be06-e38eefcb8c80")]
        public partial class StartAppFolder : RepoGenBaseFolder
        {
            DelTek_POCRepositoryFolders.PaneRootFolder _paneroot;
            RepoItemInfo _containerhashInfo;
            RepoItemInfo _textdInfo;
            AppsListInfoClass _appslistInfo;
            GroupItemsInfoClass _groupitemsInfo;
            RepoItemInfo _recentlistInfo;

            /// <summary>
            /// Creates a new Start  folder.
            /// </summary>
            public StartAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Start", "/winapp[@appid='App']", parentFolder, 30000, null, true, "bcf9319b-b30d-46ff-be06-e38eefcb8c80", "")
            {
                _paneroot = new DelTek_POCRepositoryFolders.PaneRootFolder(this);
                _containerhashInfo = new RepoItemInfo(this, "ContainerHash", ".//list[@automationid='AppsList']/container[@caption='#']", 30000, null, "478182eb-1af2-4b7e-95c1-bfeed523cdb1");
                _textdInfo = new RepoItemInfo(this, "TextD", ".//list[@automationid='ZoomAppsList']/listitem[@name='D']/text[@name='D']", 30000, null, "c4adc11e-9fb6-4f59-a385-8be45a3d66ca");
                _appslistInfo = new AppsListInfoClass(this);
                _groupitemsInfo = new GroupItemsInfoClass(this);
                _recentlistInfo = new RepoItemInfo(this, "RecentList", ".//list[@automationid='AppsList']/container[@automationid='RecentList']", 30000, null, "df7e7440-dc1d-426a-93eb-dc892a436c08");
            }

            /// <summary>
            /// The AppsListInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("3ceabf9d-33dc-4d59-9a22-f6b214c9065a")]
            public class AppsListInfoClass : RepoItemInfo
            {
                /// <summary>
                /// AppsListInfoClass class constructor.
                /// </summary>
                public AppsListInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "AppsList", "?/?/element[@automationid='ZoomControl']/list[@automationid='AppsList']", 30000, null, "3ceabf9d-33dc-4d59-9a22-f6b214c9065a")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("85345919-a577-486f-a9a1-c81afab350b1")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("85345919-a577-486f-a9a1-c81afab350b1");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("85345919-a577-486f-a9a1-c81afab350b1")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("85345919-a577-486f-a9a1-c81afab350b1", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <returns>The Screenshot2 image.</returns>
                [RepositoryImage("3cd7a0d1-217d-4e33-95b6-0b658d99a964")]
                public CompressedImage GetScreenshot2()
                {
                    return GetImage("3cd7a0d1-217d-4e33-95b6-0b658d99a964");
                }

                /// <summary>
                /// Gets the Screenshot2 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("3cd7a0d1-217d-4e33-95b6-0b658d99a964")]
                public CompressedImage GetScreenshot2(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("3cd7a0d1-217d-4e33-95b6-0b658d99a964", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <returns>The Screenshot3 image.</returns>
                [RepositoryImage("d0d81f4e-8c18-40a0-85db-67b6c70b53de")]
                public CompressedImage GetScreenshot3()
                {
                    return GetImage("d0d81f4e-8c18-40a0-85db-67b6c70b53de");
                }

                /// <summary>
                /// Gets the Screenshot3 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("d0d81f4e-8c18-40a0-85db-67b6c70b53de")]
                public CompressedImage GetScreenshot3(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("d0d81f4e-8c18-40a0-85db-67b6c70b53de", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <returns>The Screenshot4 image.</returns>
                [RepositoryImage("90e2c630-9b62-40ee-ac41-bb096b20b365")]
                public CompressedImage GetScreenshot4()
                {
                    return GetImage("90e2c630-9b62-40ee-ac41-bb096b20b365");
                }

                /// <summary>
                /// Gets the Screenshot4 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("90e2c630-9b62-40ee-ac41-bb096b20b365")]
                public CompressedImage GetScreenshot4(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("90e2c630-9b62-40ee-ac41-bb096b20b365", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot5 item image.
                /// </summary>
                /// <returns>The Screenshot5 image.</returns>
                [RepositoryImage("51ff7e97-f8f7-443c-8cee-1fc52ca1e1d9")]
                public CompressedImage GetScreenshot5()
                {
                    return GetImage("51ff7e97-f8f7-443c-8cee-1fc52ca1e1d9");
                }

                /// <summary>
                /// Gets the Screenshot5 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("51ff7e97-f8f7-443c-8cee-1fc52ca1e1d9")]
                public CompressedImage GetScreenshot5(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("51ff7e97-f8f7-443c-8cee-1fc52ca1e1d9", cropRect);
                }

                /// <summary>
                /// Gets the Screenshot6 item image.
                /// </summary>
                /// <returns>The Screenshot6 image.</returns>
                [RepositoryImage("ca7ad6a0-f91d-4646-91a9-760c16466c42")]
                public CompressedImage GetScreenshot6()
                {
                    return GetImage("ca7ad6a0-f91d-4646-91a9-760c16466c42");
                }

                /// <summary>
                /// Gets the Screenshot6 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("ca7ad6a0-f91d-4646-91a9-760c16466c42")]
                public CompressedImage GetScreenshot6(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("ca7ad6a0-f91d-4646-91a9-760c16466c42", cropRect);
                }
            }

            /// <summary>
            /// The GroupItemsInfoClass folder.
            /// </summary>
            [RepositoryItemInfo("24175746-0e77-49d5-a8e3-73cd0bf28b3f")]
            public class GroupItemsInfoClass : RepoItemInfo
            {
                /// <summary>
                /// GroupItemsInfoClass class constructor.
                /// </summary>
                public GroupItemsInfoClass(RepoGenBaseFolder parentFolder)
                    : base(parentFolder, "GroupItems", "?/?/list[@automationid='groupItems']", 30000, null, "24175746-0e77-49d5-a8e3-73cd0bf28b3f")
                { }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <returns>The Screenshot1 image.</returns>
                [RepositoryImage("fcd0c474-efaa-48ab-8269-9586915b5a62")]
                public CompressedImage GetScreenshot1()
                {
                    return GetImage("fcd0c474-efaa-48ab-8269-9586915b5a62");
                }

                /// <summary>
                /// Gets the Screenshot1 item image.
                /// </summary>
                /// <param name="cropRect">The bounds of the sub-image to return.</param>
                /// <returns>The cropped image.</returns>
                [RepositoryImage("fcd0c474-efaa-48ab-8269-9586915b5a62")]
                public CompressedImage GetScreenshot1(System.Drawing.Rectangle cropRect)
                {
                    return GetImage("fcd0c474-efaa-48ab-8269-9586915b5a62", cropRect);
                }
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bcf9319b-b30d-46ff-be06-e38eefcb8c80")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bcf9319b-b30d-46ff-be06-e38eefcb8c80")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ContainerHash item.
            /// </summary>
            [RepositoryItem("478182eb-1af2-4b7e-95c1-bfeed523cdb1")]
            public virtual Ranorex.Container ContainerHash
            {
                get
                {
                    return _containerhashInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The ContainerHash item info.
            /// </summary>
            [RepositoryItemInfo("478182eb-1af2-4b7e-95c1-bfeed523cdb1")]
            public virtual RepoItemInfo ContainerHashInfo
            {
                get
                {
                    return _containerhashInfo;
                }
            }

            /// <summary>
            /// The TextD item.
            /// </summary>
            [RepositoryItem("c4adc11e-9fb6-4f59-a385-8be45a3d66ca")]
            public virtual Ranorex.Text TextD
            {
                get
                {
                    return _textdInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TextD item info.
            /// </summary>
            [RepositoryItemInfo("c4adc11e-9fb6-4f59-a385-8be45a3d66ca")]
            public virtual RepoItemInfo TextDInfo
            {
                get
                {
                    return _textdInfo;
                }
            }

            /// <summary>
            /// The AppsList item.
            /// </summary>
            [RepositoryItem("3ceabf9d-33dc-4d59-9a22-f6b214c9065a")]
            public virtual Ranorex.List AppsList
            {
                get
                {
                    return _appslistInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The AppsList item info.
            /// </summary>
            [RepositoryItemInfo("3ceabf9d-33dc-4d59-9a22-f6b214c9065a")]
            public virtual AppsListInfoClass AppsListInfo
            {
                get
                {
                    return _appslistInfo;
                }
            }

            /// <summary>
            /// The GroupItems item.
            /// </summary>
            [RepositoryItem("24175746-0e77-49d5-a8e3-73cd0bf28b3f")]
            public virtual Ranorex.List GroupItems
            {
                get
                {
                    return _groupitemsInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The GroupItems item info.
            /// </summary>
            [RepositoryItemInfo("24175746-0e77-49d5-a8e3-73cd0bf28b3f")]
            public virtual GroupItemsInfoClass GroupItemsInfo
            {
                get
                {
                    return _groupitemsInfo;
                }
            }

            /// <summary>
            /// The RecentList item.
            /// </summary>
            [RepositoryItem("df7e7440-dc1d-426a-93eb-dc892a436c08")]
            public virtual Ranorex.Container RecentList
            {
                get
                {
                    return _recentlistInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The RecentList item info.
            /// </summary>
            [RepositoryItemInfo("df7e7440-dc1d-426a-93eb-dc892a436c08")]
            public virtual RepoItemInfo RecentListInfo
            {
                get
                {
                    return _recentlistInfo;
                }
            }

            /// <summary>
            /// The PaneRoot folder.
            /// </summary>
            [RepositoryFolder("fe2a2309-ccea-45e1-8b18-3c1778fababd")]
            public virtual DelTek_POCRepositoryFolders.PaneRootFolder PaneRoot
            {
                get { return _paneroot; }
            }
        }

        /// <summary>
        /// The PaneRootFolder folder.
        /// </summary>
        [RepositoryFolder("fe2a2309-ccea-45e1-8b18-3c1778fababd")]
        public partial class PaneRootFolder : RepoGenBaseFolder
        {
            RepoItemInfo _powerbuttonInfo;
            RepoItemInfo _windowsimmersivecontrolpanelcw5n1h2txyInfo;
            RepoItemInfo _navigationpaneInfo;

            /// <summary>
            /// Creates a new PaneRoot  folder.
            /// </summary>
            public PaneRootFolder(RepoGenBaseFolder parentFolder) :
                    base("PaneRoot", "?/?/form[@automationid='PaneRoot']", parentFolder, 30000, null, false, "fe2a2309-ccea-45e1-8b18-3c1778fababd", "")
            {
                _powerbuttonInfo = new RepoItemInfo(this, "PowerButton", "?/?/listitem[@automationid='PowerButton']", 30000, null, "f511daf4-fbfc-4ae5-9d7d-2da8dd04bf74");
                _windowsimmersivecontrolpanelcw5n1h2txyInfo = new RepoItemInfo(this, "WindowsImmersivecontrolpanelCw5n1h2txy", "?/?/listitem[@automationid='windows.immersivecontrolpanel_cw5n1h2txyewy!microsoft.windows.immersivecontrolpanel']", 30000, null, "556f9b2d-4e7c-4012-b457-4d9b52b51347");
                _navigationpaneInfo = new RepoItemInfo(this, "NavigationPane", "list[@automationid='NavigationPane']", 30000, null, "d17e3ef3-2b1d-4e68-8cf1-79de13014cd0");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("fe2a2309-ccea-45e1-8b18-3c1778fababd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("fe2a2309-ccea-45e1-8b18-3c1778fababd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PowerButton item.
            /// </summary>
            [RepositoryItem("f511daf4-fbfc-4ae5-9d7d-2da8dd04bf74")]
            public virtual Ranorex.ListItem PowerButton
            {
                get
                {
                    return _powerbuttonInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The PowerButton item info.
            /// </summary>
            [RepositoryItemInfo("f511daf4-fbfc-4ae5-9d7d-2da8dd04bf74")]
            public virtual RepoItemInfo PowerButtonInfo
            {
                get
                {
                    return _powerbuttonInfo;
                }
            }

            /// <summary>
            /// The WindowsImmersivecontrolpanelCw5n1h2txy item.
            /// </summary>
            [RepositoryItem("556f9b2d-4e7c-4012-b457-4d9b52b51347")]
            public virtual Ranorex.ListItem WindowsImmersivecontrolpanelCw5n1h2txy
            {
                get
                {
                    return _windowsimmersivecontrolpanelcw5n1h2txyInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The WindowsImmersivecontrolpanelCw5n1h2txy item info.
            /// </summary>
            [RepositoryItemInfo("556f9b2d-4e7c-4012-b457-4d9b52b51347")]
            public virtual RepoItemInfo WindowsImmersivecontrolpanelCw5n1h2txyInfo
            {
                get
                {
                    return _windowsimmersivecontrolpanelcw5n1h2txyInfo;
                }
            }

            /// <summary>
            /// The NavigationPane item.
            /// </summary>
            [RepositoryItem("d17e3ef3-2b1d-4e68-8cf1-79de13014cd0")]
            public virtual Ranorex.List NavigationPane
            {
                get
                {
                    return _navigationpaneInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The NavigationPane item info.
            /// </summary>
            [RepositoryItemInfo("d17e3ef3-2b1d-4e68-8cf1-79de13014cd0")]
            public virtual RepoItemInfo NavigationPaneInfo
            {
                get
                {
                    return _navigationpaneInfo;
                }
            }
        }

        /// <summary>
        /// The DHS_FormAppFolder folder.
        /// </summary>
        [RepositoryFolder("7b48ef68-bac7-43b6-8b0c-e24b9cd1e438")]
        public partial class DHS_FormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closebuttonInfo;
            RepoItemInfo _installbuttonInfo;
            RepoItemInfo _firstcategoryInfo;
            RepoItemInfo _getmoresupportlinkInfo;

            /// <summary>
            /// Creates a new DHS_Form  folder.
            /// </summary>
            public DHS_FormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DHS_Form", "/form[@wpfnative='True' and @name='mainWindow']", parentFolder, 30000, null, true, "7b48ef68-bac7-43b6-8b0c-e24b9cd1e438", "")
            {
                _closebuttonInfo = new RepoItemInfo(this, "CloseButton", "?/?/container[@automationid='TitleBar']/container[3]/button[2]", 30000, null, "09f96891-50d2-429e-aaab-12105605f39e");
                _installbuttonInfo = new RepoItemInfo(this, "InstallButton", ".//container[@automationid='DriversStackPanel']//button", 30000, null, "86368588-93ae-48c3-8877-81ce992004c2");
                _firstcategoryInfo = new RepoItemInfo(this, "FirstCategory", "element[@automationid='FirstCategory']/?/?/container", 30000, null, "1edd0a99-0229-467f-adfd-404d491d9172");
                _getmoresupportlinkInfo = new RepoItemInfo(this, "GetMoreSupportLink", ".//container[@automationid='contentManagementControl']//text[@automationid='GetMoreSupportTxt']", 30000, null, "c7db2c40-5146-4259-869c-d125ead354ff");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7b48ef68-bac7-43b6-8b0c-e24b9cd1e438")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7b48ef68-bac7-43b6-8b0c-e24b9cd1e438")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CloseButton item.
            /// </summary>
            [RepositoryItem("09f96891-50d2-429e-aaab-12105605f39e")]
            public virtual Ranorex.Button CloseButton
            {
                get
                {
                    return _closebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CloseButton item info.
            /// </summary>
            [RepositoryItemInfo("09f96891-50d2-429e-aaab-12105605f39e")]
            public virtual RepoItemInfo CloseButtonInfo
            {
                get
                {
                    return _closebuttonInfo;
                }
            }

            /// <summary>
            /// The InstallButton item.
            /// </summary>
            [RepositoryItem("86368588-93ae-48c3-8877-81ce992004c2")]
            public virtual Ranorex.Button InstallButton
            {
                get
                {
                    return _installbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The InstallButton item info.
            /// </summary>
            [RepositoryItemInfo("86368588-93ae-48c3-8877-81ce992004c2")]
            public virtual RepoItemInfo InstallButtonInfo
            {
                get
                {
                    return _installbuttonInfo;
                }
            }

            /// <summary>
            /// The FirstCategory item.
            /// </summary>
            [RepositoryItem("1edd0a99-0229-467f-adfd-404d491d9172")]
            public virtual Ranorex.Container FirstCategory
            {
                get
                {
                    return _firstcategoryInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The FirstCategory item info.
            /// </summary>
            [RepositoryItemInfo("1edd0a99-0229-467f-adfd-404d491d9172")]
            public virtual RepoItemInfo FirstCategoryInfo
            {
                get
                {
                    return _firstcategoryInfo;
                }
            }

            /// <summary>
            /// The GetMoreSupportLink item.
            /// </summary>
            [RepositoryItem("c7db2c40-5146-4259-869c-d125ead354ff")]
            public virtual Ranorex.Text GetMoreSupportLink
            {
                get
                {
                    return _getmoresupportlinkInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The GetMoreSupportLink item info.
            /// </summary>
            [RepositoryItemInfo("c7db2c40-5146-4259-869c-d125ead354ff")]
            public virtual RepoItemInfo GetMoreSupportLinkInfo
            {
                get
                {
                    return _getmoresupportlinkInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}