///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DelTek_POC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DelTek_POCRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("5fdf545d-8175-4dfa-afd5-4019d1273998")]
    public partial class DelTek_POCRepository : RepoGenBaseFolder
    {
        static DelTek_POCRepository instance = new DelTek_POCRepository();

        /// <summary>
        /// Gets the singleton class instance representing the DelTek_POCRepository element repository.
        /// </summary>
        [RepositoryFolder("5fdf545d-8175-4dfa-afd5-4019d1273998")]
        public static DelTek_POCRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DelTek_POCRepository() 
            : base("DelTek_POCRepository", "/", null, 0, false, "5fdf545d-8175-4dfa-afd5-4019d1273998", ".\\RepositoryImages\\DelTek_POCRepository5fdf545d.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5fdf545d-8175-4dfa-afd5-4019d1273998")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class DelTek_POCRepositoryFolders
    {
    }
#pragma warning restore 0436
}